app/blueprints/survey/__init__.py
from .routes import survey_bp

__all__ = [
    "survey_bp"
]

app/blueprints/survey/routes.py
import json
from datetime import datetime

from flask import Blueprint, render_template, redirect, url_for, flash, request
from flask_wtf.csrf import validate_csrf

from app import db
from app.forms import FeedbackForm, SurveyForm
from app.models import ContactInfo, Survey, Committee, Answer, Record, User, Punct, Subcriterion, Criterion, Feedback
from app.schemas import SurveySchema, CommitteeSchema

survey_bp = Blueprint('survey', __name__, template_folder='templates/survey')


@survey_bp.route('/')
def index():
    surveys = Survey.query.all()
    return render_template('survey/index.html', surveys=surveys)


@survey_bp.route('/survey/<slug>', methods=['GET', 'POST'])
def take_survey(slug):
    survey_data = Survey.query.filter_by(slug=slug).first_or_404()
    survey = SurveySchema.model_validate(survey_data.to_dict())
    committees = [CommitteeSchema.model_validate(committee.to_dict()) for committee in Committee.query.all()]

    if request.method == 'POST':
        form_data = request.form.to_dict()
        print(form_data)
        with open(f"reports/json/{form_data['post']}-{form_data['subdivision']}-{form_data['committee']}", "w",
                  encoding="utf-8") as file:
            json.dump(form_data, file)
        csrf_token = form_data.get('csrf_token')
        try:
            validate_csrf(csrf_token)
        except Exception as e:
            flash("Ошибка: отсутствует или неверный CSRF токен.", 'error')
            return redirect(url_for('survey_bp.take_survey', slug=slug))

        try:
            new_user = User(
                post=form_data["post"],
                subdivision=form_data["subdivision"],
                committee_id=form_data["committee"],
                created_at=datetime.utcnow()
            )
            db.session.add(new_user)
            db.session.flush()

            user_record = Record(user_id=new_user.id, survey_id=survey_data.id, created_at=datetime.utcnow())
            db.session.add(user_record)
            db.session.flush()

            answers = {}

            allowed_values = [i * 0.25 for i in range(0, 17)]

            for key, value in form_data.items():
                if key.startswith("criterion_") and key.endswith("_response"):
                    try:
                        question_number = int(key.split("_")[1])
                        answers[question_number] = {"comment": value}
                    except (IndexError, ValueError):
                        print(f"Ошибка при обработке ключа {key}: некорректный формат.")
                        continue

                elif key.endswith("-range"):
                    if key.startswith("criterion_"):
                        try:
                            question_number = int(key.split("_")[1].split("-")[0])
                            range_value = float(value)

                            if range_value in allowed_values:
                                if question_number not in answers:
                                    answers[question_number] = {}
                                answers[question_number]["range_value"] = range_value
                            else:
                                print(
                                    f"Ошибка при обработке значения {value} для {key}: значение должно быть одним из {allowed_values}.")
                        except (IndexError, ValueError) as e:
                            print(f"Ошибка при обработке значения {value} для {key}: некорректный формат. E: {e}")

                    else:
                        try:
                            question_number = int(key.split("-")[0])
                            range_value = float(value)

                            if range_value in allowed_values:
                                if question_number not in answers:
                                    answers[question_number] = {}
                                answers[question_number]["range_value"] = range_value
                            else:
                                print(
                                    f"Ошибка при обработке значения {value} для {key}: значение должно быть одним из {allowed_values}.")
                        except (IndexError, ValueError) as e:
                            print(f"Ошибка при обработке значения {value} для {key}: некорректный формат. E: {e}")

                elif "-radio" in key:
                    split_key = key.split("-")
                    if len(split_key) > 1:
                        try:
                            question_number = int(split_key[0])
                            range_min_value = float(value)
                            subcriterion = db.session.query(Subcriterion).filter_by(
                                question_number=question_number).first()

                            if subcriterion:
                                punct = db.session.query(Punct).filter_by(subcriterion_id=subcriterion.id,
                                                                          range_min=range_min_value).first()
                                if punct:
                                    punct_id = punct.id
                                    if question_number not in answers:
                                        answers[question_number] = {}
                                    answers[question_number].update({
                                        "punct_id": punct_id,
                                        "answer_value": range_min_value
                                    })
                        except ValueError:
                            print(f"Ошибка при обработке значения {value} для {key}: некорректный формат.")
                            continue

                elif key.endswith("-textarea") or key.endswith("-comment"):
                    split_key = key.split("-")
                    if len(split_key) > 1:
                        try:
                            question_number = int(split_key[0])
                            if question_number not in answers:
                                answers[question_number] = {}
                            answers[question_number]["comment"] = value
                        except ValueError:
                            print(f"Ошибка при обработке значения {value} для {key}: некорректный формат.")
                            continue

            for question_number, answer_data in answers.items():
                criterion_id = next(
                    (criterion.id for direction in survey_data.directions
                     for criterion in direction.criterions
                     if criterion.question_number == question_number),
                    None
                )

                subcriterion_id = next(
                    (sc.id for direction in survey_data.directions
                     for criterion in direction.criterions
                     for sc in criterion.subcriterions
                     if sc.question_number == question_number),
                    None
                )

                if subcriterion_id and not criterion_id:
                    criterion_id = next(
                        (criterion.id for direction in survey_data.directions
                         for criterion in direction.criterions
                         for sc in criterion.subcriterions
                         if sc.id == subcriterion_id),
                        None
                    )

                is_detailed_response_required = (
                        (criterion_id and db.session.query(Criterion)
                         .filter_by(id=criterion_id, detailed_response=True)
                         .first()) or
                        (subcriterion_id and db.session.query(Subcriterion)
                         .filter_by(id=subcriterion_id, detailed_response=True)
                         .first())
                )

                if is_detailed_response_required and "comment" not in answer_data:
                    flash(f"Вопрос {question_number} требует развернутого ответа.", 'error')
                    return redirect(url_for('survey_bp.take_survey', slug=slug))

                answer = Answer(
                    record_id=user_record.id,
                    criterion_id=criterion_id,
                    subcriterion_id=subcriterion_id,
                    punct_id=answer_data.get("punct_id"),
                    answer_value=answer_data.get("answer_value"),
                    range_value=answer_data.get("range_value"),
                    comment=answer_data.get("comment")
                )
                print(answer.to_dict())
                db.session.add(
                    answer
                )

            db.session.commit()
            flash("Ваши ответы успешно сохранены", 'success')
            return redirect(url_for('survey.index'))

        except Exception as e:
            db.session.rollback()
            flash(f"Произошла ошибка при сохранении ответов: {str(e)}", 'error')

    return render_template('survey/one_page.html', survey=survey, committees=committees, form=SurveyForm())


@survey_bp.route('/about')
def about():
    return render_template('survey/about.html', title='О сайте')


@survey_bp.route('/feedback', methods=['GET', 'POST'])
def feedback():
    form = FeedbackForm()
    contact_info = ContactInfo.query.first()
    if form.validate_on_submit():
        new_feedback = Feedback(
            name=form.name.data,
            email=form.email.data,
            message=form.message.data
        )
        db.session.add(new_feedback)
        db.session.commit()
        flash('Ваше сообщение было отправлено.', 'success')
        return redirect(url_for('survey.feedback'))
    return render_template('survey/feedback.html', form=form, title='Обратная связь', contact_info=contact_info)


@survey_bp.route('/privacy')
def privacy():
    return render_template('survey/privacy.html', title='Политика конфиденциальности')

app/templates/survey/about.html
{% extends 'survey/base.html' %}

{% block content %}
{{ super() }}
    <div class="">
        <h1 class="text-center">О нас</h1>
        <p>Сайт сделан специально для проведения данного опроса. Для получения обратной связи, перейдите на странуцу "Обратная связь".</p>
        <div class="col-sm-6 mb-3 mb-sm-0">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Исходный код сайта</h5>
                    <p class="card-text">Исходный код сайта можно найти на Github.</p>
                    <a href="https://github.com/dobrodelete/Survey" class="btn btn-primary">Посмотреть на Github</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/survey/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/docs.css') }}">
    <script src="{{ url_for('static', filename='script/bootstrap.bundle.min.js') }}"></script>
    <title>{{ title }}</title>
</head>
<body>
    <div class="container d-flex flex-column justify-content-center align-items-center pb-lg-5" style="max-width: 1200px;">
        {% include 'survey/header_nav.html' %}
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                <ul class=flashes>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
                </ul>
            {% endif %}
        {% endwith %}
        {% block content -%}
        {% endblock %}
    </div>
</body>
<script src="{{ url_for('static', filename='script/script.js') }}"></script>
</html>

app/templates/survey/feedback.html
{% extends 'survey/base.html' %}

{% block content %}
{{ super() }}
    <h1 class="text-center">Обратная связь</h1>
    <form action="{{ url_for('survey.feedback') }}" class="w-100" method="post">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.name.label(class="form-label") }}
            {{ form.name(class="form-control w-100") }}
        </div>
        <div class="form-group">
            {{ form.email.label(class="form-label") }}
            {{ form.email(class="form-control w-100") }}
        </div>
        <div class="form-group mb-3">
            {{ form.message.label(class="form-label") }}
            {{ form.message(class="form-control w-100") }}
        </div>
        <div>
            {{ form.submit(class="btn btn-primary") }}
        </div>
    </form>
    <hr>
    {% if contact_info %}
        <p>Если у вас возникли вопросы или предложения, вы можете обратиться по следующим адресам:</p>
        <ul>
            <li>Email: {{ contact_info.email }}</li>
            <li>Телефон: {{ contact_info.phone }}</li>
        </ul>
    {% else %}
        <p>Контактная информация временно недоступна.</p>
    {% endif %}

{% endblock %}

app/templates/survey/header_nav.html
{% block nav %}
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{ url_for('survey.index') }}">Опрос для ИОГВ</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{{ url_for('survey.about') }}">О сайте</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{{ url_for('survey.feedback') }}">Обратная связь</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% endblock %}

app/templates/survey/index.html
{% extends 'survey/base.html' %}
{% block content %}
<div class="container-sm">
    {% for survey in surveys %}
        <div class="card m-5">
            <h5 class="card-header">{{ survey.title }}</h5>
            <div class="card-body">
                <p class="card-text">{{ survey.introduction|safe }}</p>
                <a href="{{ url_for('survey.take_survey', slug=survey.slug) }}" class="btn btn-primary">Пройти опрос</a>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock %}

app/templates/survey/login.html
{% extends 'site/base.html' %}

{% block content %}
{{ super() }}
    <form class="w-100" action="{{ url_for('survey.instruction') }}" method="post">
        {% include 'site/components/iogv_registration.html' %}
        <input class="btn btn-primary" type="submit" value="Регистрация">
    </form>
{% endblock %}

app/templates/survey/one_page.html
{% extends 'survey/base.html' %}
{% block content %}
<form method="post" id="surveyForm">
    {{ form.hidden_tag() }}
    {{ form.csrf_token }}
    <div>
        <h1 class="text-center">Регистрация</h1>
        <div>
            <div class="mb-3">
                <label for="committeeSelect" class="form-label">Комитет</label>
                <select id="committeeSelect" name="committee" class="form-select">
                    {% for committee in committees %}
                    <option value="{{ committee.id }}">{{ committee.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="mb-3">
                <label for="subdivisionInput" class="form-label">Подразделение</label>
                <input type="text" id="subdivisionInput" name="subdivision" class="form-control">
            </div>
            <div class="mb-3">
                <label for="postInput" class="form-label">Должность</label>
                <input type="text" id="postInput" name="post" class="form-control">
            </div>
            <div class="form-group form-check mb-3">
                <input type="checkbox" id="privacyCheckbox" name="privacy" class="form-check-input">
                <label for="privacyCheckbox" class="form-check-label">Я подтверждаю <a href="/privacy">политику конфиденциальности</a></label>
            </div>
        </div>
    </div>

    <div>
        {% for instruction in survey.survey_instructions %}
            <p>{{ instruction.body_html|safe }}</p>
        {% endfor %}
    </div>
    <h1>Опрос</h1>
    {% for direction in survey.directions %}
        <div class="card mb-4">
            <div class="card-header">
                <h3>{{ direction.title }}</h3>
            </div>
            <div class="card-body">
                {% for criterion in direction.criterions %}
                    <div class="card mb-3">
                        <div class="card-header">
                            <h4>{{ criterion.title }}</h4>
                        </div>
                        <div class="card-body">
                            {% if criterion.is_interview %}
                                <div class="interview-section mb-4">
                                    <label for="criterion_{{ criterion.question_number }}_response" class="form-label">
                                        {{ criterion.question or "Дайте развернутый ответ на вопрос." }}
                                    </label>
                                    <textarea class="form-control"
                                              id="criterion_{{ criterion.question_number }}_response"
                                              name="criterion_{{ criterion.question_number }}_response"
                                              rows="4"
                                              required></textarea>

                                    <label for="criterion_{{ criterion.question_number }}_range" class="form-label mt-2">
                                        Оцените от 0 до 4
                                    </label>
                                    <input type="range" class="form-range"
                                           id="criterion_{{ criterion.question_number }}_range"
                                           name="criterion_{{ criterion.question_number }}-range"
                                           min="0" max="4" step="0.25"
                                           oninput="displayRangeValue(this.value, 'criterion_{{ criterion.question_number }}_range_value')">
                                    <span id="criterion_{{ criterion.question_number }}_range_value">2.0</span>
                                </div>
                            {% endif %}


                            {% for subcriterion in criterion.subcriterions %}
                                <div class="subcriterion mb-4">
                                    <p><strong>{{ subcriterion.title }} - Вес: {{ subcriterion.weight }}</strong></p>

                                    {% if subcriterion.is_interview %}
                                        <div class="interview-section mb-4">
                                            <label for="subcriterion_{{ subcriterion.question_number }}_response" class="form-label">
                                                {{ subcriterion.question or "Дайте развёрнутый ответ на вопрос." }}
                                            </label>
                                            <textarea class="form-control"
                                                      id="subcriterion_{{ subcriterion.question_number }}_response"
                                                      name="subcriterion_{{ subcriterion.question_number }}_response"
                                                      rows="4"
                                                      required></textarea>
                                        </div>
                                    {% else %}
                                        {% for punct in subcriterion.puncts %}
                                            <div class="punct form-check">
                                                <input type="radio"
                                                       id="score_{{ punct.id }}"
                                                       name="{{ subcriterion.question_number }}-radio"
                                                       value="{{ punct.range_min }}"
                                                       class="form-check-input"
                                                       data-question-id="{{ subcriterion.question_number }}"
                                                       onchange="printRadioValue(this.value, this.id)"
                                                       required>
                                                <label class="form-check-label" for="score_{{ punct.id }}"
                                                       {% if punct.prompt %} title="{{ punct.prompt }}" {% endif %}>
                                                    {{ punct.title }} ({{ punct.range_min }} - {{ punct.range_max }})
                                                </label>
                                            </div>
                                        {% endfor %}

                                        <div class="d-flex align-items-center range-question form-check form-check-inline">
                                            <input type="range"
                                                   class="m-2"
                                                   onchange="printRangeValue(this.value, this.id)"
                                                   oninput="printRangeValue(this.value, this.id)"
                                                   data-question-id="{{ subcriterion.question_number }}"
                                                   name="{{ subcriterion.question_number }}-range"
                                                   id="{{ subcriterion.question_number }}-range"
                                                   value="0"
                                                   min="0"
                                                   max="1"
                                                   step="0.25">
                                            <label id="{{ subcriterion.question_number }}-range-label">Ваша градация: 0</label>
                                        </div>
                                    {% endif %}

                                    <div id="{{ subcriterion.question_number }}-comment-container"></div>
                                    <button type="button"
                                            id="{{ subcriterion.question_number }}-add-button"
                                            class="btn btn-secondary btn-sm"
                                            data-question-id="{{ subcriterion.question_number }}"
                                            onclick="addComment(this.id)">Добавить комментарий</button>
                                    <button type="button"
                                            id="{{ subcriterion.question_number }}-delete-button"
                                            class="btn btn-danger btn-sm"
                                            style="display: none;"
                                            data-question-id="{{ subcriterion.question_number }}"
                                            onclick="deleteComment(this.id)">Удалить комментарий</button>
                                </div>
                            {% endfor %}

                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endfor %}
    <button type="submit" class="btn btn-primary">Отправить ответы</button>
</form>


{% endblock %}

app/templates/survey/page404.html
{% extends 'site/base.html' %}

{% block content %}
{{ super() }}
<p>Страница не найдена, вернуться на <a href="{{ url_for('site.index') }}">главную</a> страницу</p>
{% endblock %}

app/templates/survey/privacy.html
{% extends 'survey/base.html' %}

{% block content %}
{{ super() }}
    <div class="">
        <h1 class="text-center">Политика конфеденциальности и обработка персональных данных.</h1>
        <p>Мы ценим вашу конфиденциальность и уделяем большое внимание безопасности ваших персональных данных.</p>
        <p>Вся информация, которую вы предоставляете на нашем сайте, используется исключительно для обработки и анализа предоставленных вами данных, которые хранятся на серверах <a href="https://iac.spb.ru/">СПб ГУП «СПб ИАЦ»</a>.</p>
        <p>Мы не передаем вашу информацию третьим лицам без вашего явного согласия.</p>
    </div>
{% endblock %}

app/templates/survey/start.html
{% extends 'site/base.html' %}

{% block content %}
{{ super() }}
    <form id="form" action="{{ url_for('survey.start') }}" method="post">
        {% include 'site/components/iogv_survey.html' %}
    </form>
{% endblock %}

app/templates/survey/survey.html
{% extends "survey/base.html" %}

{% block content %}
<h2>{{ title }}</h2>

<form method="POST" action="">
    {{ registration_form.hidden_tag() }}
    <div>
        {{ registration_form.iogv.label }} {{ registration_form.iogv() }}
    </div>
    <div>
        {{ registration_form.subdivision.label }} {{ registration_form.subdivision() }}
    </div>
    <div>
        {{ registration_form.post.label }} {{ registration_form.post() }}
    </div>
    <div>
        {{ registration_form.privacy.label }} {{ registration_form.privacy() }}
    </div>

    <hr>

    
    <div>
        <h1 class="text-center">Инструкция по заполнению</h1>
        <p>Уважаемы респондент!</p>
        <p>Вопросы по оценке цифровой зрелости разделены на шесть направлений (разделов):</p>
        <ol>
            <li>Организационная культура и управление (вопросы 1-13)</li>
            <li>Кадры (вопросы 14-28)</li>
            <li>Процессы (вопросы 29-37)</li>
            <li>Продукты (вопросы 38-48)</li>
            <li>Данные (вопросы 49-60)</li>
            <li>Инфраструктура и инструменты (вопросы 61-66)</li>
        </ol>
        <p>В разделах представлено 66 вопросов (от 6 до 15 в каждом), необходимо выполнить 2 действия:</p>
        <ol>
            <li>выбрать утверждение, которое на Ваш взгляд наиболее точно описывает текущее состояние;</li>
            <li>использовать подвижную шкалу для точного выбора значения (с разбивкой по уровням, шаг 0,25). Необходимо установить шкалу в соответствии с оценкой, которую Вы выбрали для каждого вопроса.</li>
        </ol>
        <p>Модель оценки – дискретная от 0 до 4, где 4 это максимально возможная оценка.</p>
    
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th rowspan="2">Критерий</th>
                    <th rowspan="2">Ранг (ваша оценка)</th>
                    <th colspan="4">Уровень цифровой зрелости</th>
                </tr>
                <tr>
                    <th>0-1</th>
                    <th>1-2</th>
                    <th>2-3</th>
                    <th>3-4</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Степень понимания инструкции по заполнению анкеты по ЦТ</td>
                    <td></td>
                    <td>Понимания заполнения нет, либо оно носит фрагментарный характер</td>
                    <td>Есть общее понимание по заполнению</td>
                    <td>Понимание по заполнению есть, но существуют вопросы к деталям</td>
                    <td>Все предельно понятно</td>
                </tr>
            </tbody>
        </table>
    
        <ul>
            <li>да, формулировка полностью соответствует (2,0);</li>
            <li>скорее да, чем нет (1,75);</li>
            <li>затрудняюсь ответить (1,5);</li>
            <li>скорее нет, чем да (1,25);</li>
            <li>нет, формулировка полностью не соответствует (1,0).</li>
        </ul>
    
        <p>Системный подход при реализации мероприятий по повышению уровня цифровой зрелости на уровне города позволит выполнить точечную настройку существующих государственных информационных систем, внедрить единый подход при переходе от функциональной к процессной модели управления ИОГВ, значительно повысить эффективность при межведомственном взаимодействии, обеспечить направление комплексных заявок на обучение.</p>
    </div>
    
    <hr>

    {{ survey_form.hidden_tag() }}
    {% for direction in survey_form.directions %}
        <h3>{{ direction.title.label }}</h3>
        {% for criterion in direction.criterions %}
            <div>
                <h4>{{ criterion.title.label }}</h4>
                {% for subcriterion in criterion.subcriteria %}
                    <div>
                        <label>{{ subcriterion.title.label }} ({{ subcriterion.question_number.data }})</label>
                        <div>{{ subcriterion.radio_buttons() }}</div>
                        <div>{{ subcriterion.comments.label }}: {{ subcriterion.comments() }}</div>
                    </div>
                {% endfor %}
            </div>
        {% endfor %}
    {% endfor %}
    <hr>
    <button type="submit">{{ survey_form.submit.label }}</button>
</form>
{% endblock %}